baseURL: "https://aceticia.github.io"
title: Chris Liu
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
  tag: tags

menu:
  main:
    - name: Papers
      url: papers/
      weight: 2
    - name: Blog
      url: blogs/
      weight: 6

params:
  description: "This website hosts Chris Liu's research papers, blogs, CV, and contact information."
  author: Chris Liu
  # googleAnalyticsID: "G-XXXXX"
  DateFormat: "January 2006"
  defaultTheme: light
  hideFooter: false
  disableThemeToggle: true
  ShowShareButtons: false
  ShowReadingTime: false
  disableSpecial1stPost: true
  disableAnchoredHeadings: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowAllPagesInArchive: false
  MainSections: ["papers", "blogs"]
  ShowToc: false
  disableScrollToTop: true
  TocOpen: true
  ShowWordCount: false
  UseHugoToc: true
  comments: false
  math: true
  profileMode:
    enabled: true
    title: Chris Liu
    subtitle: "I'm a PhD student in the Department of Electrical and Computer Engineering at New York University. I'm interested in computational and clinical neuroscience, and I'm passionate about using data and modeling to drive scientific discovery and real-world impact."
    imageUrl: "picture.png"
    imageWidth: 160
    imageHeight: 160
    buttons:
      - name: Papers
        url: papers/
      - name: Archive
        url: archive/
      - name: Blog
        url: blogs/

  socialIcons:
    - name: CV
      url: cv.pdf
    - name: Email
      url: mailto:chris.liu@nyu.edu
    - name: Google Scholar
      url: https://scholar.google.com/citations?user=ZY-JsPoAAAAJ&hl
    - name: GitHub
      url: https://github.com/aceticia
    - name: LinkedIn
      url: https://www.linkedin.com/in/xujin-chris-liu-6a050616b/

  assets:
    disableScrollBarStyle: true
  cover:
    hiddenInList: false
    hiddenInSingle: true
  label:
    text: "Chris Liu"
    icon: favicon.ico
    iconHeight: 18

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    guessSyntax: true
    style: autumn
  tableOfContents:
    endLevel: 2
    ordered: false
    startLevel: 2
